>P1;4llu_AB
sequence:4llu_AB.pdb:1::440:human:Pertuzumab:10.1038/NBT.2797:2.16 ANGSTROMS:0.225
EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLEWVADVNPNSGGSIY
NQRFKGRFTLSVDRSKNTLYLQMNSLRAEDTAVYYCARNLGPSFYFDYWGQGTLVTVSSA
STKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSG
LYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHT/DIQMTQSPSSLSA
SVGDRVTITCKASQDVSIGVAWYQQKPGKAPKLLIYSASYRYTGVPSRFSGSGSGTDFTL
TISSLQPEDFATYYCQQYYIYPYTFGQGTKVEIKGQPKAAPSVTLFPPSSEELQANKATL
VCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYS
CQVTHEGSTVEKTVAPTEC
*
>P1;1s78_D
structureX:1s78_D.pdb:1:D:216:human:Pertuzumab:10.1016/S1535-6108(04)00083-2:3.25 ANGSTROMS:0.227
EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLEWVADVNPNSGGSIY
NQRFKGRFTLSVDRSKNTLYLQMNSLRAEDTAVYYCARNLGPSFYFDYWGQGTLVTVSSA
STKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSG
LYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
>P1;4llw_B
structureX:4llw_B.pdb:1:B:210:human:Pertuzumab:10.1038/NBT.2797:1.95 ANGSTROMS:0.212
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------DIQMTQSPSSLSA
SVGDRVTITCKASQDVSIGVAWYQRKPGKAPKLLIYSASYRYTGVPSRFSGSGSGTDFTL
TISSLQPEDFATYYCQQYYIYPYTFGQGTKVEIKGQPKAAPSVTLFPPSSEELQANKATL
VCLISDFYPGAVTVAWKADSSPVKAGVETTTPSK---NKYAASSYLSLTPEQWKSHRSYS
CQVTHEGSTVEKTVAPT--
*

