>P1;4llu_AB

EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLEWVADVNPNSGGSIY
NQRFKGRFTLSVDRSKNTLYLQMNSLRAEDTAVYYCARNLGPSFYFDYWGQGTLVTVSSA
STKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSG
LYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTDIQMTQSPSSLSA
SVGDRVTITCKASQDVSIGVAWYQQKPGKAPKLLIYSASYRYTGVPSRFSGSGSGTDFTL
TISSLQPEDFATYYCQQYYIYPYTFGQGTKVEIKGQPKAAPSVTLFPPSSEELQANKATL
VCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYS
CQVTHEGSTVEKTVAPTEC
*
>P1;4llw_B

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------DIQMTQSPSSLSA
SVGDRVTITCKASQDVSIGVAWYQRKPGKAPKLLIYSASYRYTGVPSRFSGSGSGTDFTL
TISSLQPEDFATYYCQQYYIYPYTFGQGTKVEIKGQPKAAPSVTLFPPSSEELQANKATL
VCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYS
CQVTHEGSTVEKTVAPTEC
*
