>P1;target

EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLEWVADVNPNSGGSIY
NQRFKGRFTLSVDRSKNTLYLQMNSLRAEDTAVYYCARNLGPSFYFDYWGQGTLVTVSSA
STKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSG
LYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTDIQMTQSPSSLSA
SVGDRVTITCKASQDVSIGVAWYQQKPGKAPKLLIYSASYRYTGVPSRFSGSGSGTDFTL
TISSLQPEDFATYYCQQYYIYPYTFGQGTKVEIKGQPKAAPSVTLFPPSSEELQANKATL
VCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYS
CQVTHEGSTVEKTVAPTEC
*
>P1;7CZT_H

QVQLVESGGGVVQPGRSLRLSCAASGFTFSSYGMHWVRQAPGKGLEWVAVIWYDGSNKYY
ADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARWFHTGGYFDYWGQGTLVTVSSA
STKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSG
LYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHT-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
*
